CREATE TABLE IF NOT EXISTS collection_examples (
    id UUID PRIMARY KEY,
    collection_id UUID NOT NULL,
    request_id UUID NOT NULL,
    name VARCHAR NOT NULL,
    slug VARCHAR NOT NULL,
    method VARCHAR NOT NULL,
    url TEXT NOT NULL,
    query_params BLOB NULL,
    path_variables BLOB NULL,
    auth BLOB NULL,
    headers BLOB NULL,
    body BLOB NULL,
    response_body TEXT NULL,
    response_headers BLOB NULL,
    response_cookies BLOB NULL,
    status INT,
    status_text VARCHAR,
    idx INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE,
    FOREIGN KEY (request_id) REFERENCES collection_requests(id) ON DELETE CASCADE
);
